# Correct configuration for a Next.js site on Netlify
[build]
  command = "npm run build"
  publish = ".next"

# The Netlify Plugin for Next.js is essential for correct routing, server-side rendering, and other features.
[[plugins]]
  package = "@netlify/plugin-nextjs"
