name: Deploy to Windsurf

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - name: Deploy to Windsurf
        uses: windsurf-actions/deploy@v1
        with:
          project-id: ${{ secrets.WINDSURF_PROJECT_ID }}
          api-key: ${{ secrets.WINDSURF_API_KEY }}
