name: Deploy to Windsurf

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - name: Deploy to Windsurf
        env:
          WINDSURF_API_KEY: ${{ secrets.WINDSURF_API_KEY }}
          WINDSURF_PROJECT_ID: ${{ secrets.WINDSURF_PROJECT_ID }}
        run: |
          curl -X POST "https://api.windsurf.build/api/v1/deployments" \
            -H "Authorization: Bearer $WINDSURF_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"project_id\": \"$WINDSURF_PROJECT_ID\", \"source\": \"github\", \"commit_sha\": \"${{ github.sha }}\"}"
