name: Deploy to Windsurf

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - name: Deploy to Windsurf
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.WINDSURF_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"projectId": "${{ secrets.WINDSURF_PROJECT_ID }}"}' \
            https://api.windsurf.com/deploy
