name: Deploy to Windsurf

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Windsurf
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.WINDSURF_TOKEN }}" \
            -F "files=@.next" \
            https://api.windsurf.xyz/deploy?project_id=tota-ai
